name: GitGcrImage
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login in 
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GCRIOTOKEN }}
      - name: Docker pull and push
        run: |
          docker pull registry.k8s.io/metrics-server/metrics-server:v0.6.4
          docker pull gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/controller:v0.53.0
          docker pull gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/entrypoint:v0.53.0
          docker pull gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/nop:v0.53.0
          docker pull gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/sidecarlogresults:v0.53.0
          docker pull gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/workingdirinit:v0.53.0
          docker pull gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/events:v0.53.0
          docker pull gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/resolvers:v0.53.0
          docker pull gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/webhook:v0.53.0
          docker pull cgr.dev/chainguard/busybox:latest
          docker pull gcr.io/tekton-releases/github.com/tektoncd/dashboard/cmd/dashboard:v0.41.0@sha256:698b458f98789177571182b8d092d49e44cd814ab8bbd3434e6ea66d538196c1
          

          docker tag gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/controller:v0.53.0   ghcr.io/ganweilong/gci_image/tekton-releases/github.com/tektoncd/pipeline/cmd/controller:v0.53.0
          docker tag gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/entrypoint:v0.53.0   ghcr.io/ganweilong/gci_image/tekton-releases/github.com/tektoncd/pipeline/cmd/entrypoint:v0.53.0 
          docker tag gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/nop:v0.53.0          ghcr.io/ganweilong/gci_image/tekton-releases/github.com/tektoncd/pipeline/cmd/nop:v0.53.0
          docker tag gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/sidecarlogresults:v0.53.0 ghcr.io/ganweilong/gci_image/tekton-releases/github.com/tektoncd/pipeline/cmd/sidecarlogresults:v0.53.0
          docker tag gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/workingdirinit:v0.53.0 ghcr.io/ganweilong/gci_image/tekton-releases/github.com/tektoncd/pipeline/cmd/workingdirinit:v0.53.0
          docker tag gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/resolvers:v0.53.0   ghcr.io/ganweilong/gci_image/tekton-releases/github.com/tektoncd/pipeline/cmd/resolvers:v0.53.0
          docker tag gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/webhook:v0.53.0  ghcr.io/ganweilong/gci_image/tekton-releases/github.com/tektoncd/pipeline/cmd/webhook:v0.53.0
          docker tag registry.k8s.io/metrics-server/metrics-server:v0.6.4 ghcr.io/ganweilong/gci_image/metrics-server/metrics-server:v0.6.4
          docker tag gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/events:v0.53.0 ghcr.io/ganweilong/gci_image/tekton-releases/github.com/tektoncd/pipeline/cmd/events:v0.53.0
          docker tag  cgr.dev/chainguard/busybox:latest ghcr.io/ganweilong/gci_image/chainguard/busybox:latest
          docker tag gcr.io/tekton-releases/github.com/tektoncd/dashboard/cmd/dashboard:v0.41.0@sha256:698b458f98789177571182b8d092d49e44cd814ab8bbd3434e6ea66d538196c1 ghcr.io/ganweilong/gci_image/tekton-releases/github.com/tektoncd/dashboard/cmd/dashboard:v0.41.0
          
          docker push ghcr.io/ganweilong/gci_image/tekton-releases/github.com/tektoncd/pipeline/cmd/controller:v0.53.0
          docker push   ghcr.io/ganweilong/gci_image/tekton-releases/github.com/tektoncd/pipeline/cmd/entrypoint:v0.53.0 
          docker push         ghcr.io/ganweilong/gci_image/tekton-releases/github.com/tektoncd/pipeline/cmd/nop:v0.53.0
          docker push ghcr.io/ganweilong/gci_image/tekton-releases/github.com/tektoncd/pipeline/cmd/sidecarlogresults:v0.53.0
          docker push ghcr.io/ganweilong/gci_image/tekton-releases/github.com/tektoncd/pipeline/cmd/workingdirinit:v0.53.0
          docker push   ghcr.io/ganweilong/gci_image/tekton-releases/github.com/tektoncd/pipeline/cmd/resolvers:v0.53.0
          docker push  ghcr.io/ganweilong/gci_image/tekton-releases/github.com/tektoncd/pipeline/cmd/webhook:v0.53.0
          docker push ghcr.io/ganweilong/gci_image/metrics-server/metrics-server:v0.6.4
          docker push ghcr.io/ganweilong/gci_image/tekton-releases/github.com/tektoncd/pipeline/cmd/events:v0.53.0
          docker push ghcr.io/ganweilong/gci_image/chainguard/busybox:latest
          docker push ghcr.io/ganweilong/gci_image/tekton-releases/github.com/tektoncd/dashboard/cmd/dashboard:v0.41.0
